# Generated by Django 4.2.7 on 2024-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_art',
            field=models.ImageField(default='default_cover.jpg', upload_to=''),
        ),
    ]
