FROM python:3.10.12-slim-bullseye

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
COPY ./setup/requirements.txt .
RUN pip install -r requirements.txt

COPY ./startup.sh .
RUN sed -i 's/\r$//g' /usr/src/app/startup.sh
RUN chmod +x /usr/src/app/startup.sh

COPY . .

ENTRYPOINT ["/usr/src/app/startup.sh"]